name: tracking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter_iconly: 1.0.2
  flutter_feather_icons: ^2.0.0+1
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.0.9
  location: ^4.3.0
  camera: ^0.9.2+2
  path_provider: ^2.0.4
  path: ^1.8.0
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.5
  background_locator: ^1.6.6
  location_permissions: ^4.0.0
  background_location: ^0.8.1
  permission_handler: ^8.0.1
  equatable: ^2.0.3
  device_info: ^2.0.2
  intl: ^0.17.0
  date_range_picker: ^1.0.7
  firebase_core: "^1.7.0"
  firebase_messaging: "^10.0.8"
  flutter_local_notifications: ^9.0.2
  firebase_core_web: ^1.1.0
  scrollable_positioned_list: ^0.2.2
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.10
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
